name: Test code
on:
  push:
    branches:
      - master
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.SUBMODULES_PAT_TOKEN }}

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: dotnet restore
        run: dotnet restore

      - name: dotnet build
        run: dotnet build -c Debug -p:GeneratePackageOnBuild=false

      - name: dotnet test
        run: |
          dotnet test -c Debug --no-restore --no-build --logger "console;verbosity=detailed"
